---
categories: Analysis
tags: [error]
---

## pywin32
엑셀 파일을 열어 특정 지표를 가져오는 과정에서

`module 'win32com.gen_py.00020813-0000-0000-C000-000000000046x0x1x9' has no attribute 'CLSIDToClassMap'` 라는 오류가 떴다.

[stackoverflow](https://stackoverflow.com/questions/52889704/python-win32com-excel-com-model-started-generating-errors) 를 참고해 오류를 해결했다.


<br><br>

`python -c "import win32com; print(win32com.__gen_path__)"`를 실행해 

출력된 해당 위치에 오류가 나는 "00020813-0000-0000-C000-000000000046x0x1x9" 폴더를 제거한 후 실행했더니 정상적으로 동작했다.
